package com.SolarShare.service;

import java.io.ByteArrayOutputStream;
import java.time.LocalDate;

import org.springframework.stereotype.Service;

import com.SolarShare.model.RooftopListing;
import com.SolarShare.model.UserInfo;
import com.SolarShare.model.UserType;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

@Service
public class AgreementPdfService {

    public byte[] generateSampleAgreement(RooftopListing listing, UserInfo homeowner, UserInfo company) {
        try (ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            Document document = new Document(new Rectangle(595, 842), 54, 54, 56, 56);
            PdfWriter.getInstance(document, output);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.TIMES_BOLD, 17);
            Font subtitleFont = FontFactory.getFont(FontFactory.TIMES_ROMAN, 10);
            Font sectionFont = FontFactory.getFont(FontFactory.TIMES_BOLD, 12);
            Font labelFont = FontFactory.getFont(FontFactory.TIMES_BOLD, 10);
            Font bodyFont = FontFactory.getFont(FontFactory.TIMES_ROMAN, 11);
            Font noteFont = FontFactory.getFont(FontFactory.TIMES_ITALIC, 9);

            Paragraph title = new Paragraph("ROOFTOP LEASE AND SOLAR INSTALLATION AGREEMENT", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(5f);
            document.add(title);

            Paragraph subtitle = new Paragraph("Generated by SolarShare Platform", subtitleFont);
            subtitle.setAlignment(Element.ALIGN_CENTER);
            subtitle.setSpacingAfter(14f);
            document.add(subtitle);

            PdfPTable meta = new PdfPTable(2);
            meta.setWidthPercentage(100);
            meta.setWidths(new float[]{1.2f, 2.8f});
            addTableRow(meta, "Agreement Date", LocalDate.now().toString(), labelFont, bodyFont);
            addTableRow(meta, "Agreement ID", "SSA-" + listing.getId() + "-" + LocalDate.now(), labelFont, bodyFont);
            addTableRow(meta, "Jurisdiction", safe(listing.getCity()) + ", India", labelFont, bodyFont);
            meta.setSpacingAfter(12f);
            document.add(meta);

            addSectionHeading(document, "1. Parties", sectionFont);
            document.add(new Paragraph(
                    "This Rooftop Lease and Solar Installation Agreement (\"Agreement\") is entered into between the parties below:",
                    bodyFont));
            document.add(new Paragraph(" "));

            PdfPTable parties = new PdfPTable(2);
            parties.setWidthPercentage(100);
            parties.setWidths(new float[]{1.2f, 2.8f});
            addTableRow(parties, "Homeowner", safe(homeowner.getFullName()), labelFont, bodyFont);
            addTableRow(parties, "Solar Company", resolveDisplayName(company), labelFont, bodyFont);
            parties.setSpacingAfter(10f);
            document.add(parties);

            addSectionHeading(document, "2. Property Details", sectionFont);
            PdfPTable property = new PdfPTable(2);
            property.setWidthPercentage(100);
            property.setWidths(new float[]{1.2f, 2.8f});
            addTableRow(property, "Site Address", safe(listing.getAddress()), labelFont, bodyFont);
            addTableRow(property, "City", safe(listing.getCity()), labelFont, bodyFont);
            addTableRow(property, "Rooftop Area", safeNumber(listing.getAreaSquareFt()) + " sq.ft", labelFont, bodyFont);
            addTableRow(property, "Monthly Lease Rent", "INR " + safeNumber(listing.getExpectedRent()), labelFont, bodyFont);
            property.setSpacingAfter(10f);
            document.add(property);

            addSectionHeading(document, "3. Core Terms and Conditions", sectionFont);
            addClause(document,
                    "3.1 Term",
                    "The initial term of this Agreement shall be 11 (eleven) months from the Effective Date and may be renewed by mutual written consent.",
                    bodyFont);
            addClause(document,
                    "3.2 Scope of Use",
                    "The Solar Company is granted a limited right to install, operate, and maintain rooftop solar infrastructure on the designated property area.",
                    bodyFont);
            addClause(document,
                    "3.3 Rent and Payment",
                    "Monthly lease rent shall be paid to the Homeowner on or before the 7th day of each calendar month by mutually agreed banking mode.",
                    bodyFont);
            addClause(document,
                    "3.4 Compliance",
                    "Both parties shall comply with applicable municipal laws, electrical safety standards, and regulatory requirements.",
                    bodyFont);
            addClause(document,
                    "3.5 Access and Maintenance",
                    "The Homeowner shall provide reasonable access for installation and maintenance upon prior notice, except in emergencies.",
                    bodyFont);
            addClause(document,
                    "3.6 Termination",
                    "Either party may terminate this Agreement for material breach after providing written notice and a reasonable cure period.",
                    bodyFont);

            addSectionHeading(document, "4. Declarations", sectionFont);
            document.add(new Paragraph(
                    "Both parties confirm that they have read and understood this Agreement and agree to be bound by its terms.",
                    bodyFont));
            document.add(new Paragraph(" "));

            PdfPTable signature = new PdfPTable(2);
            signature.setWidthPercentage(100);
            signature.setWidths(new float[]{1f, 1f});
            signature.setSpacingBefore(8f);

            PdfPCell homeownerCell = new PdfPCell();
            homeownerCell.setBorder(Rectangle.NO_BORDER);
            homeownerCell.addElement(new Paragraph("For Homeowner", labelFont));
            homeownerCell.addElement(new Paragraph("\nSignature: __________________________", bodyFont));
            homeownerCell.addElement(new Paragraph("Name: " + safe(homeowner.getFullName()), bodyFont));
            homeownerCell.addElement(new Paragraph("Date: _______________________________", bodyFont));

            PdfPCell companyCell = new PdfPCell();
            companyCell.setBorder(Rectangle.NO_BORDER);
            companyCell.addElement(new Paragraph("For Solar Company", labelFont));
            companyCell.addElement(new Paragraph("\nSignature: __________________________", bodyFont));
            companyCell.addElement(new Paragraph("Company Name: " + resolveDisplayName(company), bodyFont));
            companyCell.addElement(new Paragraph("Authorized Signatory: " + safe(company.getFullName()), bodyFont));
            companyCell.addElement(new Paragraph("Date: _______________________________", bodyFont));

            signature.addCell(homeownerCell);
            signature.addCell(companyCell);
            document.add(signature);

            Paragraph note = new Paragraph(
                    "Note: This is a system-generated sample agreement for workflow use and should be reviewed by a qualified legal professional before execution.",
                    noteFont);
            note.setSpacingBefore(18f);
            note.setAlignment(Element.ALIGN_JUSTIFIED);
            document.add(note);

            document.close();
            return output.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Could not generate agreement PDF", e);
        }
    }

        public byte[] generateClusterAgreement(
            com.SolarShare.model.ClusterProject project,
            RooftopListing listing,
            UserInfo homeowner,
            UserInfo company) {
        try (ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            Document document = new Document(new Rectangle(595, 842), 54, 54, 56, 56);
            PdfWriter.getInstance(document, output);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.TIMES_BOLD, 17);
            Font subtitleFont = FontFactory.getFont(FontFactory.TIMES_ROMAN, 10);
            Font sectionFont = FontFactory.getFont(FontFactory.TIMES_BOLD, 12);
            Font labelFont = FontFactory.getFont(FontFactory.TIMES_BOLD, 10);
            Font bodyFont = FontFactory.getFont(FontFactory.TIMES_ROMAN, 11);
            Font noteFont = FontFactory.getFont(FontFactory.TIMES_ITALIC, 9);

            Paragraph title = new Paragraph("ROOFTOP CLUSTER PARTICIPATION AGREEMENT", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(5f);
            document.add(title);

            Paragraph subtitle = new Paragraph("Generated by SolarShare Platform", subtitleFont);
            subtitle.setAlignment(Element.ALIGN_CENTER);
            subtitle.setSpacingAfter(14f);
            document.add(subtitle);

            PdfPTable meta = new PdfPTable(2);
            meta.setWidthPercentage(100);
            meta.setWidths(new float[]{1.2f, 2.8f});
            addTableRow(meta, "Agreement Date", LocalDate.now().toString(), labelFont, bodyFont);
            addTableRow(meta, "Cluster Project", safe(project.getProjectName()), labelFont, bodyFont);
            addTableRow(meta, "Cluster City", safe(project.getCity()), labelFont, bodyFont);
            addTableRow(meta, "Agreement ID", "CLG-" + project.getId() + "-" + listing.getId(), labelFont, bodyFont);
            meta.setSpacingAfter(12f);
            document.add(meta);

            addSectionHeading(document, "1. Parties", sectionFont);
            document.add(new Paragraph(
                "This Cluster Participation Agreement (\"Agreement\") is entered into between the rooftop owner and the Solar Company creating the cluster.",
                bodyFont));
            document.add(new Paragraph(" "));

            PdfPTable parties = new PdfPTable(2);
            parties.setWidthPercentage(100);
            parties.setWidths(new float[]{1.2f, 2.8f});
            addTableRow(parties, "Rooftop Owner", safe(homeowner.getFullName()), labelFont, bodyFont);
            addTableRow(parties, "Solar Company", resolveDisplayName(company), labelFont, bodyFont);
            parties.setSpacingAfter(10f);
            document.add(parties);

            addSectionHeading(document, "2. Rooftop Contribution", sectionFont);
            PdfPTable property = new PdfPTable(2);
            property.setWidthPercentage(100);
            property.setWidths(new float[]{1.2f, 2.8f});
            addTableRow(property, "Site Address", safe(listing.getAddress()), labelFont, bodyFont);
            addTableRow(property, "City", safe(listing.getCity()), labelFont, bodyFont);
            addTableRow(property, "Contribution Area", safeNumber(listing.getAreaSquareFt()) + " sq.ft", labelFont, bodyFont);
            addTableRow(property, "Contribution Rent", "INR " + safeNumber(listing.getExpectedRent()), labelFont, bodyFont);
            addTableRow(property, "Cluster Target", safeNumber(project.getTargetArea()) + " sq.ft", labelFont, bodyFont);
            property.setSpacingAfter(10f);
            document.add(property);

            addSectionHeading(document, "3. Cluster Terms", sectionFont);
            addClause(document,
                "3.1 Conditional Effectiveness",
                "This Agreement becomes binding only when the cluster reaches its target capacity and SolarShare marks the cluster as full.",
                bodyFont);
            addClause(document,
                "3.2 Opt-Out Window",
                "The rooftop owner may opt out only before the cluster becomes full and before this Agreement is generated.",
                bodyFont);
            addClause(document,
                "3.3 Exclusivity",
                "Once the cluster becomes full, the rooftop shall remain reserved for the cluster and shall not be available for separate independent use during the agreement term.",
                bodyFont);
            addClause(document,
                "3.4 Revenue and Payment",
                "The monthly contribution rent shall remain payable as displayed in the listing and recorded in SolarShare.",
                bodyFont);
            addClause(document,
                "3.5 Compliance",
                "Both parties shall comply with applicable safety, municipal, and electrical regulations throughout the cluster term.",
                bodyFont);

            addSectionHeading(document, "4. Declarations", sectionFont);
            document.add(new Paragraph(
                "The rooftop owner acknowledges that participation is voluntary until the cluster is full, and the Solar Company acknowledges responsibility to manage cluster coordination in good faith.",
                bodyFont));
            document.add(new Paragraph(" "));

            PdfPTable signature = new PdfPTable(2);
            signature.setWidthPercentage(100);
            signature.setWidths(new float[]{1f, 1f});
            signature.setSpacingBefore(8f);

            PdfPCell homeownerCell = new PdfPCell();
            homeownerCell.setBorder(Rectangle.NO_BORDER);
            homeownerCell.addElement(new Paragraph("For Rooftop Owner", labelFont));
            homeownerCell.addElement(new Paragraph("\nSignature: __________________________", bodyFont));
            homeownerCell.addElement(new Paragraph("Name: " + safe(homeowner.getFullName()), bodyFont));
            homeownerCell.addElement(new Paragraph("Date: _______________________________", bodyFont));

            PdfPCell companyCell = new PdfPCell();
            companyCell.setBorder(Rectangle.NO_BORDER);
            companyCell.addElement(new Paragraph("For Solar Company", labelFont));
            companyCell.addElement(new Paragraph("\nSignature: __________________________", bodyFont));
            companyCell.addElement(new Paragraph("Company Name: " + resolveDisplayName(company), bodyFont));
            companyCell.addElement(new Paragraph("Authorized Signatory: " + safe(company.getFullName()), bodyFont));
            companyCell.addElement(new Paragraph("Date: _______________________________", bodyFont));

            signature.addCell(homeownerCell);
            signature.addCell(companyCell);
            document.add(signature);

            Paragraph note = new Paragraph(
                "Note: This is a system-generated cluster agreement. It is created only after the cluster reaches full capacity.",
                noteFont);
            note.setSpacingBefore(18f);
            note.setAlignment(Element.ALIGN_JUSTIFIED);
            document.add(note);

            document.close();
            return output.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Could not generate cluster agreement PDF", e);
        }
        }

    private void addSectionHeading(Document document, String text, Font sectionFont) throws Exception {
        Paragraph heading = new Paragraph(text, sectionFont);
        heading.setSpacingBefore(7f);
        heading.setSpacingAfter(5f);
        heading.setAlignment(Element.ALIGN_LEFT);
        document.add(heading);
    }

    private void addClause(Document document, String heading, String content, Font bodyFont) throws Exception {
        Paragraph clause = new Paragraph();
        clause.setAlignment(Element.ALIGN_JUSTIFIED);
        clause.setSpacingAfter(4f);
        clause.add(new Phrase(heading + ": ", FontFactory.getFont(FontFactory.TIMES_BOLD, 11)));
        clause.add(new Phrase(content, bodyFont));
        document.add(clause);
    }

    private void addTableRow(PdfPTable table, String label, String value, Font labelFont, Font bodyFont) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, labelFont));
        labelCell.setPadding(6f);
        labelCell.setBorderWidth(0.8f);

        PdfPCell valueCell = new PdfPCell(new Phrase(value, bodyFont));
        valueCell.setPadding(6f);
        valueCell.setBorderWidth(0.8f);

        table.addCell(labelCell);
        table.addCell(valueCell);
    }

    private String safeNumber(Number value) {
        return value == null ? "N/A" : String.valueOf(value);
    }

    private String safe(String value) {
        return value == null ? "N/A" : value;
    }

    private String resolveDisplayName(UserInfo user) {
        if (user == null) {
            return "N/A";
        }
        if (user.getType() == UserType.SOLAR_COMPANY && user.getCompanyName() != null && !user.getCompanyName().isBlank()) {
            return user.getCompanyName();
        }
        return safe(user.getFullName());
    }
}
